server:
  port: 8081
spring:
  profiles:
    active:
  # DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/epidemic_situation?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mappers/*.xml
jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "qwertyuiop7418520" #秘钥：secret用来进行jwt的签发和jwt的验证
  expireTime: 60 #token有效时间（分钟）建议一小时上
